name: nova_google_services_core
description: A core set of classes to use in other nova google services packages
version: 2.0.0
repository: 'https://github.com/nova-flutter/nova_google_services_core'
issue_tracker: 'https://github.com/nova-flutter/nova_google_services_core/issues'


environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  http: ^1.1.2
  logging: ^1.2.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
